# [shell]
# program = "/usr/bin/fish"

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true

[colors.primary]
background = "#293136"
foreground = "#ebdbb2"

[colors.normal]
black = "#293136"
red = "#e67e80"
green = "#A7C080"
yellow = "#EABD5F"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#83a598"
white = "#ebdbb2"

[colors.bright]
black = "#293136"
red = "#fb4934"
green = "#A7C080"
yellow = "#EABD5F"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#83a598"
white = "#ebdbb2"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
# columns = 0
# lines = 0
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 3
y = 0
